# Kaimen Configuration

IGNORE_ENABLED = true

# Comma seperated directories to index
DIRS = [ ]

# Add account credentials if need be (ToDo: document this)
[[boards]]

    NAME = 'Danbooru'

    URL = 'https://danbooru.donmai.us/posts.json?limit=1&tags=md5%3A'

    API_PARAMS = '&login=%s&api_key=%s'

    TAG_KEY = 'tag_string'

[[boards]]

    NAME = 'Gelbooru'

    URL = 'https://gelbooru.com/index.php?json=1&limit=1&page=dapi&s=post&q=index&tags=md5%3A'

    API_PARAMS = '&user_id=%s&api_key=%s'

    TAG_KEY = 'tags'

[[boards]]

    NAME = 'Sakugabooru'

    URL = 'https://www.sakugabooru.com/post.json?limit=1&tags=md5%3A'

    API_PARAMS = '&login=%s&api_key=%s'

    TAG_KEY = 'tags'

[[boards]]

    NAME = 'Yandere'

    URL = 'https://yande.re/post.json?limit=1&tags=md5%3A'

    TAG_KEY = 'tags'
